project_id = "rrlmiapghsswywyxayhd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54324

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

[functions.extract-document-text]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54330