// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrlmiapghsswywyxayhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJybG1pYXBnaHNzd3l3eXhheWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDMzNjQsImV4cCI6MjA3MjkxOTM2NH0.dU5Xucu2pYpRXn0WtiKinQ0E3o_hZg3-80uYQvZ1vB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});